#!/usr/bin/python3

import cgi

print("Content-Type: text/html")
print("Status: 200 OK")
print()

form = cgi.FieldStorage()

if "cur" in form:
    cur = int(form["cur"].value)
else: 
    cur = 0;

print("""
<html>
<head>
<title>Basic CGI</title>
</head>
<body>

<center>
<h1>Basic CGI</h1>
<p><h2>Counter: {}<h2>
<a href="basicCGI?cur={}">Go up</a>
<br>
<a href="basicCGI?cur={}">Go down</a>
</center>

</body>
</html>        
""".format(cur,cur+1,cur-1))
