#! /usr/bin/python3
  
print("Content-Type: text/html")
print("Status: 200 OK")
print()

print("<html>")
print("<head>")
print("<title>First CGI Script</title>")
print("</head>")
print("<body>")
print("<center><h1>First CGI Script</h1><center>")
print("</body>")
print("</html>")

