#! /usr/bin/python3
print("Content-Type: text/html\r\n\r\n")
print("<html>")
print("<head>")
print("<title>FirstCGIScript</title>")
print("</head>")
print("<body>")
print("<center><h1>First CGI Script!</h1></center>")
print("</body>")
print("</html>")

